[package]
name = "sui-config"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
bcs = "0.1.3"
arc-swap = "1.5.0"
camino = "1.0.9"
anyhow = { version = "1.0.58", features = ["backtrace"] }
serde = { version = "1.0.140", features = ["derive", "rc"] }
serde_with = "1.14.0"
serde_yaml = "0.8.26"
rand = "0.7.3"
dirs = "4.0.0"
multiaddr = "0.14.0"
once_cell = "1.11.0"
tracing = "0.1.36"

narwhal-config = { git = "https://github.com/punwai/narwhal-1", rev = "8de998f52143fcd2c57d61ecf8d997520dd5f3f9", package = "config" }
narwhal-crypto = { git = "https://github.com/punwai/narwhal-1", rev = "8de998f52143fcd2c57d61ecf8d997520dd5f3f9", package = "crypto", features = ["zero_crypto"] }
move-binary-format = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a" }
move-package = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a" }
move-core-types = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a", features = ["address20"] }
move-vm-runtime = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a" }

sui-framework = { path = "../sui-framework" }
sui-adapter = { path = "../sui-adapter" }
sui-types = { path = "../sui-types" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
insta = { version = "1.17.1", features = ["redactions"] }
tempfile = "3.3.0"
